INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (1, 'TI', 'A1', 'Kardiale Vitien / Herzklappen');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (2, 'TI', 'A2', 'Erkrankungen der Herzkranzgefässe/Myokardinfarkt');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (3, 'TI', 'A3', 'Herz - Rhythmusstörungen');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (4, 'TI', 'A4', 'Hypertonie');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (5, 'TI', 'A5', 'Arterien');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (6, 'TI', 'A6', 'Venen (inkl. Varizen)');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (7, 'TI', 'A7', 'Lymphgefässe inkl. Lymphoedem');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (8, 'TI', 'A9', 'Andere Erkrankungen des Herz- / Kreislaufsystems');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (9, 'TI', 'B1', 'Anämie');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (10, 'TI', 'B2', 'Gerinnungsstörungen');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (11, 'TI', 'B3', 'Erkrankungen des Knochenmarks und des Blutes');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (12, 'TI', 'B4', 'Milz / Lymphknoten / Immunsystem');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (13, 'TI', 'B9', 'Andere Erkrank. von Knochenmark / Blut / Milz');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (14, 'TI', 'C1', 'Asthma');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (15, 'TI', 'C2', 'Chronischer Husten');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (16, 'TI', 'C3', 'Lungenembolie');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (17, 'TI', 'C4', 'Lunge / Pleura exkl. TBC');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (18, 'TI', 'C9', 'Andere Erkrankungen des Atemtraktes');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (19, 'TI', 'D1', 'Muskel / Sehnen');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (20, 'TI', 'D2', 'Gelenke / Bänder / Bursa exkl. D3');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (21, 'TI', 'D3', 'Arthritis / M. Bechterew');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (22, 'TI', 'D4', 'Arthrose');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (23, 'TI', 'D5', 'Wirbelsäule exkl. D3');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (24, 'TI', 'D9', 'Andere Erkrankungen des Bewegungsapparates');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (25, 'TI', 'E1', 'Oesophagus / Magen / Duodenum, inkl. Ulcera');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (26, 'TI', 'E2', 'Darm (Dünndarm / Kolon)');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (27, 'TI', 'E3', 'Rektum / Anus, inkl. Hämorrhoiden');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (28, 'TI', 'E4', 'Leber / Gallenwege / Gallenblase');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (29, 'TI', 'E5', 'Pankreas, exkl. Diabetes');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (30, 'TI', 'E6', 'Zwerchfell');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (31, 'TI', 'E7', 'Hernien');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (32, 'TI', 'E9', 'Andere Erkrankungen des Verdauungstraktes');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (33, 'TI', 'F1', 'Zuckerstoffwechsel');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (34, 'TI', 'F2', 'Erkrankungen der Schilddrüse');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (35, 'TI', 'F9', 'Andere Stoffwechselerkrankungen');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (36, 'TI', 'G1', 'Komplikationsloser Infekt');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (37, 'TI', 'G2', 'Tuberkulose');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (38, 'TI', 'G3', 'Virale Hepatitis');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (39, 'TI', 'G9', 'Andere infektiöse oder parasitäre Krankheiten');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (40, 'TI', 'H1', 'Niere / Niereninsuffizienz (Dialyse / Transplantation)');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (41, 'TI', 'H2', 'Nierensteinleiden');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (42, 'TI', 'H3', 'Ableitende Harnwege');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (43, 'TI', 'H9', 'Andere Erkrankungen der Nieren und der ableitenden Harnwege');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (44, 'TI', 'I1', 'Männliche Geschlechtsorgane');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (45, 'TI', 'I2', 'Vulva, Vagina, kleines Becken');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (46, 'TI', 'I3', 'Uterus');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (47, 'TI', 'I4', 'Adnexe');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (48, 'TI', 'I5', 'Störungen des Menstruations - Zyklus');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (49, 'TI', 'I6', 'Erkrankungen der Brustdrüse');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (50, 'TI', 'I7', 'Sterilisation');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (51, 'TI', 'I9', 'Andere Erkrankungen der Geschlechtsorgane');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (52, 'TI', 'K1', 'Schwangerschaft normales Risiko');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (53, 'TI', 'K2', 'Schwangerschaft mit Komplikation');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (54, 'TI', 'K3', 'Sterilität und künstliche Befruchtung');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (55, 'TI', 'L1', 'Hirn / Rückenmark');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (56, 'TI', 'L2', 'Periphere Nerven');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (57, 'TI', 'L3', 'Lähmung / Ataxie');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (58, 'TI', 'L4', 'Migräne und Äquivalente');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (59, 'TI', 'L5', 'Epilepsie');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (60, 'TI', 'L9', 'Andere Erkrankungen des Nervensystems');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (61, 'TI', 'M1', 'Schlafstörungen');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (62, 'TI', 'M2', 'Psychische Erkrankungen');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (63, 'TI', 'M3', 'Psychoorganische Erkrankungen');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (64, 'TI', 'N1', 'Allergische Hauterkrankungen, exkl. Ekzem');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (65, 'TI', 'N2', 'Entzündliche / infektiöse Hautkrankheiten');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (66, 'TI', 'N3', 'Ekzem');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (67, 'TI', 'N4', 'Vaskuläre / degenerative Hautkrankheiten');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (68, 'TI', 'N5', 'Psoriasis / Hyperkeratosen');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (69, 'TI', 'N6', 'Narben');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (70, 'TI', 'N9', 'Andere Hauterkrankungen');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (71, 'TI', 'O1', 'Nase exkl. N6');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (72, 'TI', 'O2', 'Nasennebenhöhlen');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (73, 'TI', 'O3', 'Mundhöhle, Speicheldrüsen');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (74, 'TI', 'O4', 'Tonsillen / Adenoide');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (75, 'TI', 'O5', 'Larynx / Trachea');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (76, 'TI', 'O6', 'Missbildungen der Nase und der Ohren');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (77, 'TI', 'O7', 'Mittelohr / Tuba Eustachii');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (78, 'TI', 'O8', 'Innenohr');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (79, 'TI', 'O9', 'Andere HNO - Erkrankungen');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (80, 'TI', 'P1', 'Lid / Konjuktiva');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (81, 'TI', 'P2', 'Linse / Kornea / Glaskörper');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (82, 'TI', 'P3', 'Iris / Glaukom');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (83, 'TI', 'P4', 'Retina / Sehnerv / Gefässe');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (84, 'TI', 'P5', 'Augenmuskeln / Strabismus');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (85, 'TI', 'P9', 'Andere Augenerkrankungen');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (86, 'TI', 'Q1', 'Zyste');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (87, 'TI', 'Q2', 'Zahnabszess');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (88, 'TI', 'Q3', 'Fibrome');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (89, 'TI', 'Q9', 'Andere Erkrankungen des Kiefers oder der Zähne');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (90, 'TI', 'R1', 'Kopf / Wirbelsäule');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (91, 'TI', 'R2', 'Thorax');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (92, 'TI', 'R3', 'Abdomen');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (93, 'TI', 'R4', 'Obere Extremität');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (94, 'TI', 'R5', 'Untere Extremität');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (95, 'TI', 'S ', 'Nicht-Pflichtleistungen');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (96, 'TI', 'T1', 'Vorsorgeuntersuchung');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (97, 'TI', 'T2', 'Impfungen');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (98, 'TI', 'U ', 'Vertrauensarzt orientiert (anstelle Diagnose)');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (99, 'TI', '01', 'Rechts');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (100, 'TI', '02', 'Links');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (101, 'TI', '03', 'Akut');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (102, 'TI', '04', 'Chronisch / Rezidiv');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (103, 'TI', '05', 'Infektiös');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (104, 'TI', '06', 'Funktionell');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (105, 'TI', '07', 'Neoplasie');
INSERT INTO referenzen.tbl_ti_code (id, typ, code, bezeichnung) VALUES (106, 'TI', '08', 'Berufsbedingt');